# Generated by Django 3.0.4 on 2020-03-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200328_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
