# Generated by Django 3.0.3 on 2020-03-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20200321_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='active',
        ),
    ]
